name: Artifact
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  upload:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact File
        run: |
          echo "This is an artifact file" > artifact.txt
          echo "Generated on $(date)" >> artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt
  download:
    name: Download Artifact
    runs-on: ubutu-latest
    needs: upload
    steps:
      - name: Download Artifact File
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Print file contents
        run: cat artifact.txt
        
  
