name: Calling .exe file

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Download exe (example)
        run: Invoke-WebRequest -Uri "https://example.com/tool.exe" -OutFile tool.exe

      - name: Run the .exe (PowerShell)
        shell: pwsh
        run: .\tool.exe --arg1 value
