name: Calling .exe file

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32

      - name: Download exe
        run: curl -L -o tool.exe https://example.com/tool.exe

      - name: Run with Wine
        run: wine tool.exe --arg1 value
